name: Validate CSV

on:
  push:
    branches: [ master ]
    paths:
    - '**.csv'
  pull_request:
    branches: [ master ]
    paths:
    - '**.csv'

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: npm ci
    - run: node scripts/validate-csv.js fallzahlen_kanton_total_csv_v2/*.csv
    - run: python scripts/check_for_outliers.py fallzahlen_kanton_total_csv_v2/*.csv
